# Generated by Django 4.0.3 on 2022-03-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_track_delete_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio',
            field=models.FileField(default='default_song.mp3', upload_to='music_file'),
        ),
        migrations.AddField(
            model_name='track',
            name='image',
            field=models.FileField(default='default_spotify.png', upload_to='music_pics'),
        ),
    ]
