# Generated by Django 4.0.3 on 2022-03-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_track_audio_track_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='image',
            field=models.ImageField(default='default_spotify.png', upload_to='music_pics'),
        ),
    ]
