# Generated by Django 4.0.3 on 2022-03-06 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('song', '0005_track_likes_track_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='likes',
        ),
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.ManyToManyField(related_name='spotify_tracks', to=settings.AUTH_USER_MODEL),
        ),
    ]
