# Generated by Django 4.0.3 on 2022-03-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_track_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
